(function ($) {
	var ua = window.navigator.userAgent;
	var isIE = /MSIE|Trident/.test(ua);

	if ( !isIE ) {
		//IE specific code goes here
		"use strict";
	}

	var homeSliderText = $('.banner-slider-wrapper .title-lg');

	if ( homeSliderText ) {
		homeSliderText.each(function() {
			var $this = $(this);
			var repeatText = $this.html().repeat(3);
			$this.html(repeatText);
		});
	}

	$('[data-toggle="tooltip"]').tooltip();

    /*** Sticky header */
	$(window).scroll(function(){
		if($("body").scrollTop() > 0 || $("html").scrollTop() > 0) {
			$(".header").addClass("stop");
		} else {
			$(".header").removeClass("stop");
		}
	});

	/*** Sticky header */
	const body = document.body;
	const scrollUp = "scroll-up";
	const scrollDown = "scroll-down";
	let lastScroll = 100;

	window.addEventListener("scroll", () => {
	  	const currentScroll = window.pageYOffset;
	  	if (currentScroll <= 0) 
	  	{
	    	body.classList.remove(scrollUp);
	    	return;
	  	}

	  	if (currentScroll > lastScroll && !body.classList.contains(scrollDown)) 
	  	{
	    	// down
	    	body.classList.remove(scrollUp);
	    	body.classList.add(scrollDown);
	  	} 
	  	else if ( currentScroll < lastScroll && body.classList.contains(scrollDown) ) 
	  	{
	    	// up
	    	body.classList.remove(scrollDown);
	    	body.classList.add(scrollUp);
	  	}

	  	lastScroll = currentScroll;
	});

	/*** Show Shop Modal */
	$('.showShopModal').click(function(){
    	$('#shop').modal('toggle')
	});

	$('body').on('show.bs.modal', function () {
        $('.sticky-top').css('margin-left', '-=0px');
    });

    $('body').on('hidden.bs.modal', function () {
        $('.sticky-top').css('margin-left', 'auto');
    });

    /*** Search bar */
	$('.header-search').on('click', '.search-toggle', function(e) {
	    e.preventDefault();
	    var selector = $(this).data('selector');
	    $(selector).toggleClass('show').find('.search-input').focus();
	});

	/*** Hover Nav menu */
    function navbarHover() {

    	var screensize = $(window).width(),
    		$header = $('.header');

	   	$('ul.navbar-nav:not(.navbar-mobile) > li.dropdown').hover(function() 
	   	{
	   		$(this).find('.dropdown-menu').show().parents('.dropdown').addClass('show');
		}, 
		function() 
		{
			var $this = $(this);

			$this.removeClass('show');

			setTimeout(function() { 
		       $this.find('.dropdown-menu').hide()
		    }, 200);
		});
    }

    $(window).on("load resize", function() {
    	navbarHover();
    });
    
	/*** Header height = gutter height */
	function setGutterHeight(){
		var header = document.querySelector('.header'),
			  gutter = document.querySelector('.header-gutter');
		if (gutter) {
			gutter.style.height = header.offsetHeight + 'px';
		}
	}
	window.onload = setGutterHeight;
	window.onresize = setGutterHeight;

    /*** ScrollDown */
	$('.scrollDown').click(function() {
	    var target = $('#primary');
	    var space = $(this).data('space');

	    if (target.length) {
	        $('html,body').animate({
	          scrollTop: target.offset().top - space
	        }, 1000);
	    }
	});

	/*** lastNobullet */
	function lastNobullet() {
	    var lastElement = false;
	    $(".last_no_bullet li").each(function() {
	        if (lastElement && lastElement.offset().top != $(this).offset().top) {
	            $(lastElement).addClass("no_bullet");
	        } else {
	            $(lastElement).removeClass("no_bullet");
	        }
	        lastElement = $(this);
	    }).last().addClass("no_bullet");
	};
	lastNobullet();

	$(window).resize(function(){
	    lastNobullet();
	});

	/*** Smooth scroll */
    $('.smoothScroll, .smoothScroll a').click(function() {
       	if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
           	var target = $(this.hash);
           	target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
           	if (target.length) {
               	$('html,body').animate({
                   scrollTop: target.offset().top - 0
               	}, 1e3, "easeInOutExpo");

               return false;
           }
       	}
    });

    function hideMaxCatItems() {

	    $('.hideMaxCatItems').hideMaxListItems({ 
			'max': 3, 
			'speed': 0, 
			'moreText': '+[COUNT]',
			'lessText': '-[COUNT]'
		});
    }  
    hideMaxCatItems();

    /*** Generated by CoffeeScript 1.9.2 */
	function stickyKit() {
	    var reset_scroll;

	    $(function() {
	        return $("[data-sticky_column]").stick_in_parent({
	            parent: "[data-sticky_parent]",
	            offset_top: 120,
	            bottoming: true,
	        });
	    });

	    reset_scroll = function() {
	        var scroller;
	        scroller = $("body,html");
	        scroller.stop(true);

	        if ($(window).scrollTop() !== 0) {
	            scroller.animate({
	                scrollTop: 0
	            }, "fast");
	        }
	        return scroller;
	    };

	    window.scroll_it = function() {
	        var max;
	        max = $(document).height() - $(window).height();

	        return reset_scroll().animate({
	            scrollTop: max
	        }, max * 3).delay(100).animate({
	            scrollTop: 0
	        }, max * 3);
	    };

	    window.scroll_it_wobble = function() {
	        var max, third;
	        max = $(document).height() - $(window).height();
	        third = Math.floor(max / 3);

	        return reset_scroll().animate({
	            scrollTop: third * 2
	        }, max * 3).delay(100).animate({
	            scrollTop: third
	        }, max * 3).delay(100).animate({
	            scrollTop: max
	        }, max * 3).delay(100).animate({
	            scrollTop: 0
	        }, max * 3);
	    };

	    $(window).on("load", (function(_this) {
	        return function(e) {
	            return $(document.body).trigger("sticky_kit:recalc");
	        };
	    })(this));

	    $(window).on("resize", (function(_this) {
	        return function(e) {
	            return $(document.body).trigger("sticky_kit:recalc");
	        };
	    })(this));
	}

	var window_width = $(window).width();

	if (window_width < 1200) {
	    $(document.body).trigger("sticky_kit:detach");
	} else {
	    stickyKit();
	}

	$( window ).resize(function() {
	    window_width = $( window ).width();
	    if (window_width < 1200) {
	        $(document.body).trigger("sticky_kit:detach");
	    } else {
	        stickyKit();
	    }
	});

	/*** banner slider */
	var bannerSlider = $('.banner-slider-wrapper');
	bannerSlider.slick({
		dots: true,
		arrows: false,
		infinite: true,
		autoplay: true,
		slidesToShow: 1,
		slidesToScroll: 1,
        cssEase:'linear',
        dotsClass: "slick-dots list-inline",
        appendDots: $(".slider-controls"),
	});

	/*** Animation */
	bannerSlider.on('init', function(e, slick) {
	  	var $firstAnimatingElements = $('div.slick-slide:first-child').find('[data-animation]');
	  	doAnimations($firstAnimatingElements);
	});

	bannerSlider.on('beforeChange', function(e, slick, currentSlide, nextSlide) {
	  	var $animatingElements = $('div.slick-slide[data-slick-index="' + nextSlide + '"]').find('[data-animation]');
	  	doAnimations($animatingElements); 
	});

	function doAnimations(elements) {
		var animationEndEvents = 'webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend';
		elements.each(function() {
			var $this = $(this);
			var $animationDelay = $this.data('delay');
			var $animationType = 'animated ' + $this.data('animation');
			$this.css({
				'animation-delay': $animationDelay,
				'-webkit-animation-delay': $animationDelay
			});
			$this.addClass($animationType).one(animationEndEvents, function() {
			  	$this.removeClass($animationType);
			});
		});
	};

	$('.modal').on('shown.bs.modal', function (e) {
	  	$('.mega-menu-slider').slick('setPosition');
	  	$('.mega-menu-slider').addClass('open');
	})

	/*** banner slider */
	var megaSlider = $('.mega-menu-slider');
	megaSlider.slick({
		dots: true,
		arrows: false,
		infinite: true,
		slidesToShow: 1,
		slidesToScroll: 1,
        dotsClass: "slick-dots list-inline",
        appendDots: $(".mega-slider-controls"),
	});

	/*** partners Slider */
    var shopmaintime = 5;
	var $shopmainbar,
		$shopmainslick,
		shopmainisPause,
		shopmaintick,
		shopmainpercentTime;

	$shopmainslick = $('.shop-main-slider');

	$shopmainslick.slick({
		autoplay: true,
		speed: 300,
  		dots: true,
  		arrows: false,
  		infinite: true,
		slidesToShow: 1, 
	  	initialSlide: 1,
	  	slidesToScroll: 1, 
	  	dotsClass: "slick-dots list-inline",
        appendDots: $(".shop-main-slider-controls"),
	})

	$shopmainbar = $('.slider-progress .progress');

	$shopmainslick.on({
		mouseenter: function() {
			shopmainisPause = true;
		},
		mouseleave: function() {
			shopmainisPause = false;
		}
	})

	function startProgressbar_partners() {
		resetProgressbar_partners();
		shopmainpercentTime = 0;
		shopmainisPause = false;
		shopmaintick = setInterval(interval_partners, 5);
	}

	function interval_partners() {
		if( shopmainisPause === false ) 
		{
			shopmainpercentTime += 1 / (shopmaintime+0.1);
			$shopmainbar.css({
				width: shopmainpercentTime+"%"
			});

			if(shopmainpercentTime >= 100)
			{
				$shopmainslick.slick('slickNext');
				startProgressbar_partners();
			}
		}
	}

	function resetProgressbar_partners() {
		$shopmainbar.css({
			width: 0+'%' 
		});
		clearTimeout(shopmaintick);
	}
	startProgressbar_partners();

	/*** mega menu product item after arrow */
	$(".product-categories > li.dropdown > a").click(function(e) {
		e.preventDefault();
		e.stopPropagation();
		var that = $(this);

		if ( that.parent().is('.show') ) 
		{
	        that.parent().removeClass( "show" );
	    }
	    else 
	    {
	        $('.product-categories > li.dropdown').removeClass( "show" );
	        that.parent().addClass( "show" );
	    }
	});

	/*** Image to SVG */
	$('img.svg').each(function(){
	    var $img = $(this);
	    var imgID = $img.attr('id');
	    var imgClass = $img.attr('class');
	    var imgURL = $img.attr('src');
	
	    $.get(imgURL, function(data) {
	        // Get the SVG tag, ignore the rest
	        var $svg = $(data).find('svg');
	
	        // Add replaced image's ID to the new SVG
	        if(typeof imgID !== 'undefined') {
	            $svg = $svg.attr('id', imgID);
	        }
	        // Add replaced image's classes to the new SVG
	        if(typeof imgClass !== 'undefined') {
	            $svg = $svg.attr('class', imgClass+' replaced-svg');
	        }
	
	        // Remove any invalid XML tags as per http://validator.w3.org
	        $svg = $svg.removeAttr('xmlns:a');
	        
	        // Check if the viewport is set, else we gonna set it if we can.
	        if(!$svg.attr('viewBox') && $svg.attr('height') && $svg.attr('width')) {
	            $svg.attr('viewBox', '0 0 ' + $svg.attr('height') + ' ' + $svg.attr('width'))
	        }
	
	        // Replace image with new SVG
	        $img.replaceWith($svg);

	        var rellax = new Rellax('.rellax');
	
	    }, 'xml');
	});

	$('.cart-popup').magnificPopup({
        type: 'inline',  
        preloader: false,
        fixedBgPos: true,
        removalDelay: 500,
        closeBtnInside: false,
        fixedContentPos: true,
        callbacks: {
            beforeOpen: function() {
                this.st.iframe.markup = this.st.iframe.markup.replace('mfp-iframe-scaler', 'mfp-iframe-scaler mfp-with-anim');
                this.st.mainClass = this.st.el.attr('data-effect');
            }
        },
        closeMarkup: '<button title="Close (Esc)" type="button" class="mfp-close icon-close"></button>',
    });

	/*** Number Counter */
	$('.counter').counterUp({
		delay: 10,
		time: 1000
	});

	var rellax = new Rellax('.rellax');

	// Call Sly on frame for summer
	var $summer_frame = $('.summer-slider-wrapper');
	var $summer_wrap  = $summer_frame.parent();

	$summer_frame.sly({
		smart: 1,
		speed: 400,
		horizontal: 1,
		mouseDragging: 1,
		releaseSwing: 1,
		touchDragging: 1,
		itemNav: 'basic',
		scrollBy: 1, 
		startAt: 0,
		swingSpeed: 0.2,
		elasticBounds: 1,
		dragHandle: 1,
		dynamicHandle: 1,
		sbSize: 80,
		activateMiddle: false,
		easing: 'easeOutExpo',
	});

	/*** BrowserDetect */
	var BrowserDetect = {
	    init: function () {
	        this.browser = this.searchString(this.dataBrowser) || "Other";
	        this.version = this.searchVersion(navigator.userAgent) || this.searchVersion(navigator.appVersion) || "Unknown";
	    },
	    searchString: function (data) {
	        for (var i = 0; i < data.length; i++) {
	            var dataString = data[i].string;
	            this.versionSearchString = data[i].subString;

	            if (dataString.indexOf(data[i].subString) !== -1) {
	                return data[i].identity;
	            }
	        }
	    },
	    searchVersion: function (dataString) {
	        var index = dataString.indexOf(this.versionSearchString);
	        if (index === -1) {
	            return;
	        }

	        var rv = dataString.indexOf("rv:");
	        if (this.versionSearchString === "Trident" && rv !== -1) {
	            return parseFloat(dataString.substring(rv + 3));
	        } else {
	            return parseFloat(dataString.substring(index + this.versionSearchString.length + 1));
	        }
	    },

	    dataBrowser: [
	        {string: navigator.userAgent, subString: "Edge", identity: "MSEdge"},
	        {string: navigator.userAgent, subString: "MSIE", identity: "Explorer"},
	        {string: navigator.userAgent, subString: "Trident", identity: "Explorer"},
	        {string: navigator.userAgent, subString: "Firefox", identity: "Firefox"},
	        {string: navigator.userAgent, subString: "Opera", identity: "Opera"},  
	        {string: navigator.userAgent, subString: "OPR", identity: "Opera"},  

	        {string: navigator.userAgent, subString: "Chrome", identity: "Chrome"}, 
	        {string: navigator.userAgent, subString: "Safari", identity: "Safari"}       
	    ]
	};
	
	BrowserDetect.init();
	document.body.classList.add( BrowserDetect.browser );


	/*** WooCommerce Quantity Increment */
	$('.woocommerce .quantity').on('click', '.icon-minus', function (e) {
        var $inputQty = $(this).parent().parent().find('input.qty');
        var $inputQtyLabel = $(this).parent().find('.label span');
        var val = parseInt($inputQty.val());
        var step = $inputQty.attr('step');

        step = 'undefined' !== typeof(step) ? parseInt(step) : 1;
        if (val > 0) {
            $inputQty.val(val - step).change();
            $inputQtyLabel.html(val - step);
        }
    });

    $('.woocommerce .quantity').on('click', '.icon-plus', function (e) {
        var $inputQty = $(this).parent().parent().find('input.qty');
        var $inputQtyLabel = $(this).parent().find('.label span');
        var val = parseInt($inputQty.val());
        var step = $inputQty.attr('step');

        step = 'undefined' !== typeof(step) ? parseInt(step) : 1;
        $inputQty.val(val + step).change();
        $inputQtyLabel.html(val + step);
    });

	/*** login */
	function loginPopup() {
		$('.login-popup').magnificPopup({
		    type: 'inline',
		    midClick: true,
		    preloader: true,
		    fixedBgPos: true,
		    removalDelay: 500,
		    fixedContentPos: true,
		    closeBtnInside: true,
		    callbacks: {
		        beforeOpen: function() {
		           this.st.mainClass = this.st.el.attr('data-effect');
		        }
		    },
		});
	}

	loginPopup();

	$('.bottom a[data-toggle="tab"]').on('click', function (e) {
	  	e.preventDefault()
	  	var target = $(e.target).attr("href");

	  	$('a[href="' + target + '"]').tab('show');
	});

   	// Auto Open If Find #url
   	if ( window.location.hash == '#register' ) {
   		$('a[href="' + window.location.hash + '"]').tab('show');
   	}

	$('.join-form-register').each(function(e) {
    	var $this = $(this);
		var $toggle = false;
    	$(this).find('.link').on('click', function(e){
	    	e.preventDefault();
	    	$this.toggleClass("show");
	    	if($toggle) {
	    		$toggle = false;
	    		setTimeout(function() {
                   $this.css("z-index", "0");
               	}, 300);
               	$this.parent().prop('style').removeProperty('height');
	    	}else {
		    	$toggle = true;
		    	$this.css("z-index", "1");
		    	$this.parent().css("height", $this.find('.text').outerHeight());
	    	}
    	});

		$(this).find('.icon-plus').on('click', function(e){
	    	e.preventDefault();
			$this.toggleClass("show");
	    	$toggle = false;
			setTimeout(function() {
				$this.css("z-index", "0");
			}, 300);
			$this.parent().prop('style').removeProperty('height');
    	});
    });

	$('button.login').click( function(event) {

	    that = $(this);

	    if (event.preventDefault) {
	        event.preventDefault();
	    } else {
	        event.returnValue = false;
	    }

	    that.text('Please wait...');

	    var reg_nonce = $('#allegheny_login_nonce').val();
	    var username  = $('#username').val();
	    var password  = $('#password').val();
	 
	    data = {
	      	action: 'user_login',
	      	nonce: reg_nonce,
	      	username: username,
	      	password: password
	    };
	 
	    // Do AJAX request
	    $.post( ajax.ajaxurl, data, function(response) {
	      	if( response ) {
	        	var data = $.parseJSON(response);
	        	if( data == 'success' ) {
	          		that.text('Redirecting...');
	          		//window.location.href = ajax.profile_page;
	          		localStorage.clear(); // clear search data to make favorite icon work
	          		location.reload();
	        	} else {
	          		$('.result-message').html(data);
	          		$('.result-message').addClass('alert-danger');
	          		$('.result-message').show();
	          		that.html('Login <i class="icon-arrow-right"></i>');
	        	}
	      	}
	    });
	});

}(jQuery));
